### ISSUE TITLE
Can select only one stop

### ISSUE THREAD

**Issue by fabrew4n** [Codestian/ha-lta#1]
Hi there.. not an issue.. but rather a question... is there options to select more than 1 bus stop?

**Comment by Codestian** [comment]
> Hi there.. not an issue.. but rather a question... is there options to select more than 1 bus stop?

For now no, but will be added in next update.

**Comment by nyy1989** [comment]
Thanks for this integration! Love it. Looking forward to seeing the multiple stops feature!

**Comment by Codestian** [comment]
Multiple stops feature has been added
