### ISSUE TITLE
New API from Mar 2025 Onwards

### ISSUE THREAD

**Issue by ttkttkttkttk** [Codestian/ha-lta#13]
Hi there, 

First off, thanks for this! Really loving the integration.
Recently received an email from LTA regarding a revision to the current API and was wondering if this integration would support the new API too? 

:)

**Comment by Codestian** [comment]
Hello,

I've checked and it appears the only revision with regards to bus arrivals is the addition of the 'monitored' property. I will add it if i have the time 👍
