### ISSUE TITLE
Not all sensors are created

### ISSUE THREAD

**Issue by fabrew4n** [Codestian/ha-lta#4]
![Screenshot_20220219-170622_Chrome](https://user-images.githubusercontent.com/47353708/154794672-750e68a1-3983-4b17-ab41-504fc5b4af09.jpg)
Hi.. I have a few bus stops set up here.. but not all sensors are created. What are the possible cause?

**Comment by fabrew4n** [comment]
![Screenshot_20220219-172448_Chrome](https://user-images.githubusercontent.com/47353708/154795032-43ea74c3-90a7-444a-8975-e4dbbb35bfe1.jpg)

**Comment by Codestian** [comment]
Have you tried configuring with less buses and bus stops? May be due to multiple call requests to the API.

**Comment by fabrew4n** [comment]
It is intermittent, sometimes the states are ok and sometimes the states are unavailable

**Comment by Codestian** [comment]
It seems that some bus services only operate at certain hours, so if it's not operating the sensor is not created or not return as unavailable. Try to create the sensors or restart HA at a time where all the buses are available (eg. not at 2am).
