### ISSUE TITLE
I failed to get the integration from HACS

### ISSUE THREAD

**Issue by Khengsoon** [Codestian/ha-lta#6]
Hi guy, I like this integration a lot. I try to get this integration from HACS but seem I'm not able to find it. At the moment I manually download. I would like to receive notification from HACS whenever there is an update. Below is my HA version. 

Home Assistant 2022.7.7
Supervisor 2022.07.0
Frontend 20220707.1 - latest

**Comment by Codestian** [comment]
Hello, this integration can only be added as a custom repository at the moment. If you would like to stay updated you can star this repository.
