### ISSUE TITLE
Error for the integration.

### ISSUE THREAD

**Issue by fabrew4n** [Codestian/ha-lta#7]
Logger: homeassistant.components.sensor
Source: custom_components/lta/sensor.py:145
Integration: Sensor (documentation, issues)
First occurred: 09:03:02 (1 occurrences)
Last logged: 09:03:02

Error while setting up lta platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/lta/sensor.py", line 145, in async_setup_platform
    BusArrivalSensor(coordinator, idx) for idx, ent in enumerate(coordinator.data)
TypeError: 'NoneType' object is not iterable

**Comment by Codestian** [comment]
Can you provide your configuration and HA version?

**Comment by fabrew4n** [comment]
![Screenshot_20220811-174933_Chrome](https://user-images.githubusercontent.com/47353708/184108268-0719253a-b2c0-47bc-b29d-b0535c9e2320.jpg)
![Screenshot_20220811-174957_Chrome](https://user-images.githubusercontent.com/47353708/184108286-5f000c33-14e2-41f7-b4a3-9b81eea59a7d.jpg)
There you go

**Comment by fabrew4n** [comment]
Hi there.. i have updated HA to the latest version. The bus sensors still the error, sometimes the integrations works ok. but then the sensors just be unavailable again.

**Comment by Codestian** [comment]
Are the bus sensors unavailable during its operational hours? Also please provide your configuration in text and HA log files with the errors. I suggest removing the above screenshots as it contains your API key.

**Comment by fabrew4n** [comment]
- platform: lta
   api_key: 'xxxxxxxxxxx'
   bus_stops:
#school#
     - code: '82181'
       buses:
         - '33'
     - code: '84019'
       buses:
         - '33'
     - code: '84231'
       buses:
         - '222'
     - code: '83169'
       buses:
         - '33'
     - code: '82061'
       buses:
         - '13'
         - '150'
         - '155

**Comment by fabrew4n** [comment]
Logger: homeassistant.components.sensor
Source: custom_components/lta/sensor.py:145
Integration: Sensor (documentation, issues)
First occurred: 19:47:32 (1 occurrences)
Last logged: 19:47:32

Error while setting up lta platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/lta/sensor.py", line 145, in async_setup_platform
    BusArrivalSensor(coordinator, idx) for idx, ent in enumerate(coordinator.data)
TypeError: 'NoneType' object is not iterable
This error originated from a custom integration.

Logger: custom_components.lta.sensor
Source: helpers/update_coordinator.py:182
Integration: lta
First occurred: 19:47:32 (1 occurrences)
Last logged: 19:47:32

Timeout fetching sensor data

**Comment by fabrew4n** [comment]
All the buses are available...

**Comment by fabrew4n** [comment]
Hi.. just to update.. the sensor are available after a home assistant core update, but the timings are off and so are the locations in the map.. 
After doing a reboot the error comes back again, and all sensors become unavailable..
