### ISSUE TITLE
error setting up sensor

### ISSUE THREAD

**Issue by mmcramos** [Codestian/ha-lta#8]
after upgrading to 10.3.  i keep on getting "unavailable" timings with detail logs below.

Logger: homeassistant.components.sensor
Source: custom_components/lta/sensor.py:195
Integration: Sensor (documentation, issues)
First occurred: 4:47:21 PM (1 occurrences)
Last logged: 4:47:21 PM

Error while setting up lta platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/lta/sensor.py", line 195, in async_setup_platform
    BusArrivalSensor(coordinator, idx) for idx, ent in enumerate(coordinator.data)
TypeError: 'NoneType' object is not iterable

**Comment by mmcramos** [comment]
Hi, see below.

sensor:
  - platform: lta
    api_key: *removed*
    bus_stops:
    - code: '67141'
      buses:
      - '86'
      - '119'
      - '136'
    - code: '67139'
      buses:
      - '119'
      - '136'

**Comment by Codestian** [comment]
I am unable to replicate this error with your config. Have you tried removing and adding ha-lta again? Make sure it's using v0.3.0.

**Comment by mmcramos** [comment]
yes, tried removing and reinstall but still same error.

**Comment by mmcramos** [comment]
yep. tried removing and putting back. i think incompatible with latest version of HA.  it was working fine when i was on 8.2
from the log looks like error is from ha python script.

Logger: homeassistant.components.sensor
Source: custom_components/lta/sensor.py:195
Integration: Sensor (documentation, issues)
First occurred: 8:21:51 PM (1 occurrences)
Last logged: 8:21:51 PM

Error while setting up lta platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/lta/sensor.py", line 195, in async_setup_platform
    BusArrivalSensor(coordinator, idx) for idx, ent in enumerate(coordinator.data)
TypeError: 'NoneType' object is not iterable

**Comment by fabrew4n** [comment]
Same issue here. Tried to reinstall and reset everything. Removed sensors from configuration and unavailable state, restart and added 1 stop, OK. Upon adding new stop and restart then the error appears. 
The image attached shows a sensor at another continent. Lol. Thou not a big issue
![Screenshot_20221015-181930_Chrome](https://user-images.githubusercontent.com/47353708/195982197-d4d06871-12df-44c6-aa46-609ea3ced249.jpg)

**Comment by Codestian** [comment]
Ok, will have to definitely look into this. Just to confirm, do the sensors work with only one bus stop configured?

**Comment by fabrew4n** [comment]
After clear off and start from scratch.. after that, restart, same thing

**Comment by mmcramos** [comment]
Hi,  this is definitely something with 10.3 HA.   I rolled back to 8.2 and it works again.   Then I upgraded again to 10.3 with my original configration.yaml from 8.2 and still works.  But when I load the 10.3 config with new MQTT: config fromat, it doesn't work again.  And when I totally delete all my other sensors, mqtt,etc leaving only lta sensor still doesn't work.  But  when I load back my original 8.2 config, works again.  I am not able to pinpoint which one is causing that HA python error.

**Comment by mmcramos** [comment]
yes. it's working fine.

**Comment by Codestian** [comment]
What do you mean by new MQTT config format?

**Comment by mmcramos** [comment]
is the new config format required for >= 10.3

https://www.home-assistant.io/integrations/binary_sensor.mqtt/#new_format
